name: dcat
description: Concatenate file(s) to standard output or file
version: 1.0.0
homepage: https://github.com/ethauvin/dcat

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.18.2
dependencies:
  args: ^2.3.0
  indent: ^2.0.0