name: dcat
description: An implementation of the standard cat Unix utility that concatenates file(s) to standard output or file.
version: 1.0.1
repository: https://github.com/ethauvin/dcat
issue_tracker: https://github.com/ethauvin/dcat/issues

environment:
  sdk: '>=2.15.1 <=3.2.3'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.18.2
dependencies:
  args: ^2.3.0
  indent: ^2.0.0
